SELECT COUNT(DISTINCT Title)
FROM Person.Person

SELECT COUNT(*)
FROM Production.Product

SELECT COUNT(size)
FROM Production.Product
-- COUNT CONTA A QUANTIDADE DE ITENS EM UM ITEM ESPECIFICO
